#minGLUT: minGLUT

#	g++ -g -Wall -o main minGLUT.cpp myArmadilloClass.cpp -lGL -lGLU -lglut -lGLEW -larmadillo


arma: minGLUT.cpp myArmadilloClass.cpp
	g++ -o arma minGLUT.cpp myArmadilloClass.cpp -lGL -lGLU -lglut -lGLEW -larmadillo

gs: gauss_seidel.cpp
	g++ -o gs gauss_seidel.cpp -lGL -lGLU -lglut -lGLEW

## DO THIS ##
# make arma
# make glut
# make main
# ./main
